name: Deploy static site to S3

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: medical-dr-web-pr   # 예: medical-dr-static-p
  CF_DIST_ID: ${{ secrets.CF_DIST_ID }}       # 선택(있으면 무효화)
  SRC_DIR: .                                  # 레포 최상단

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::077672914621:role/gitaction-go
          aws-region: ${{ env.AWS_REGION }}

      # 1) 전체 동기화 (루트 → S3), 불필요 항목 제외
      - name: Sync all to S3
        run: |
          aws s3 sync "${{ env.SRC_DIR }}/" "s3://${{ env.S3_BUCKET }}" \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".idea/*" \
            --exclude ".gitignore" \
            --exclude "README.md"

      # 2) HTML 캐시 해제 (즉시 반영)
      - name: Set no-cache for HTML
        run: |
          find "${{ env.SRC_DIR }}" -maxdepth 1 -name "*.html" -type f -print0 | xargs -0 -I {} \
            aws s3 cp "{}" "s3://${{ env.S3_BUCKET }}/$(basename "{}")" \
              --cache-control "no-cache, no-store, must-revalidate" \
              --content-type "text/html" \
              --metadata-directive REPLACE

      # 3) config.js 캐시 해제 (동적 설정이면 필수)
      - name: Set no-cache for config.js
        run: |
          if [ -f "${{ env.SRC_DIR }}/config.js" ]; then
            aws s3 cp "${{ env.SRC_DIR }}/config.js" "s3://${{ env.S3_BUCKET }}/config.js" \
              --cache-control "no-cache, no-store, must-revalidate" \
              --content-type "application/javascript" \
              --metadata-directive REPLACE
          fi

      

      # 4) CloudFront 무효화 (부분 무효화 권장)
      - name: Invalidate CloudFront
        if: env.CF_DIST_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CF_DIST_ID }} \
            --paths "/login.html" "/patients.html" "/config.js"
